import type { Metadata } from 'next'

/* Cold-traffic paid funnel: full share/SEO metadata per-route (title, desc,
   Open Graph, Twitter card). The 1200x630 og:image + twitter:image are
   generated by ./opengraph-image.tsx (Next auto-wires it). metadataBase is set
   on the root layout, so relative URLs resolve absolute.

   NOTE: kept out of the search index by design (it's a paid ad-traffic funnel,
   not a content page). To let it rank in Google, set robots.index to true. */
const TITLE = 'Build a Predictable $10K/Month Coaching Business, or 100% Money Back'
const OG_TITLE = 'Build a Predictable $10K/Month Coaching Business, Guaranteed'
const DESC =
  'You probably don’t need more content or funnels, just one fix. Find the exact bottleneck between you and a predictable $10K/month, or get 100% of your money back.'
const URL = 'https://the5th.consulting/10k-roadmap'

export const metadata: Metadata = {
  title: TITLE,
  description: DESC,
  keywords: ['coaching business', 'consultant growth', '$10K per month', 'strategy audit', 'coaching for coaches', 'predictable revenue', 'The5th Consulting'],
  alternates: { canonical: '/10k-roadmap' },
  robots: { index: false, follow: true },
  openGraph: {
    type: 'website',
    url: URL,
    siteName: 'The5th Consulting',
    title: OG_TITLE,
    description: DESC,
    // og:image is provided automatically by ./opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: 'summary_large_image',
    title: OG_TITLE,
    description: DESC,
    // twitter:image is provided automatically by ./opengraph-image.tsx.
  },
}

/* Hide third-party feedback/survey/toolbar widgets on the funnel only, and pin
   a dark theme-color so mobile browser chrome matches. */
const FUNNEL_CSS = `
  html { color-scheme: light; background:#ffffff; }
  #vercel-toolbar, vercel-live-feedback, [data-vercel-toolbar-root],
  [aria-label="Feedback" i], [aria-label*="feedback" i], [title="Feedback" i],
  iframe[title*="feedback" i], iframe[title*="survey" i],
  .cs-voc-widget, [class*="feedback-button" i], #hotjar-survey, .hj-widget-container {
    display: none !important; visibility: hidden !important;
  }
`

export default function RoadmapAuditLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <meta name="theme-color" content="#ffffff" />
      <style dangerouslySetInnerHTML={{ __html: FUNNEL_CSS }} />
      {children}
    </>
  )
}
